# Generated by Django 4.2 on 2024-03-03 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('dias_semana', models.IntegerField(choices=[(1, 'Domingo'), (2, 'Lunes'), (3, 'Martes'), (4, 'Miercoles'), (5, 'Jueves'), (6, 'Viernes'), (7, 'Sabado')])),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoAcceso',
            fields=[
                ('id_punto', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('es_activo', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcceso',
            fields=[
                ('id_tipoacceso', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('solapin', models.CharField(max_length=200)),
                ('es_activo', models.BooleanField(default=True)),
                ('rol', models.ManyToManyField(related_name='usuarios', to='api.rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_punto_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puntoacceso')),
            ],
        ),
        migrations.AddField(
            model_name='puntoacceso',
            name='tipo_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoacceso'),
        ),
    ]
